$! MAKE_KIT.COM - build the PCSI kit (x86-64)
$!
$! Usage:  @[.VMSPORT.KIT]MAKE_KIT
$! Needs a built tree (@[.VMSPORT]BUILD): the install tree
$! [.INSTALL_X86_64_CLANG] and [.OBJ_X86_64_CLANG]XMLLINT.EXE.  Writes the kit
$! to [.KIT_X86_64].  The product description, text module and documentation
$! were generated by tools/prepare.sh into [.VMSPORT.KIT].
$!
$ set noon
$ status = 44
$ saved_default = f$environment("DEFAULT")
$ proc = f$environment("PROCEDURE")
$ kitdir = f$parse(proc,,,"DEVICE") + f$parse(proc,,,"DIRECTORY")
$ set default 'kitdir'
$ set default [--]
$ base = "X86VMS"
$!
$! KIT_PRODUCER, PCSI_VERSION, KIT_VERSION from kit.env
$ open/read env [.VMSPORT.KIT]KIT.ENV
$env_loop:
$ read/end=env_done env line
$ name = f$element(0, "=", line)
$ 'name' = f$element(1, "=", line)
$ goto env_loop
$env_done:
$ close env
$!
$ inst = "[.INSTALL_X86_64_CLANG"
$ need = "''inst'.LIB]LIBXML2.OLB,''inst'.INCLUDE.LIBXML]PARSER.H,[.OBJ_X86_64_CLANG]XMLLINT.EXE"
$ i = 0
$need_loop:
$ f = f$element(i, ",", need)
$ if f .eqs. "," then goto need_done
$ if f$search(f) .eqs. ""
$ then
$   write sys$error "MAKE_KIT: no ''f'; build first"
$   goto done
$ endif
$ i = i + 1
$ goto need_loop
$need_done:
$!
$! Gather the files flat in [.KIT_X86_64.MAT]: PRODUCT PACKAGE looks each one
$! up by name in the material directory (destinations are in the PDF).
$ mat = "[.KIT_X86_64.MAT]"
$ out = "[.KIT_X86_64]"
$ if f$search("KIT_X86_64.DIR") .eqs. "" then create/directory 'out'
$ if f$search("[.KIT_X86_64]MAT.DIR") .eqs. "" then create/directory 'mat'
$ if f$search("''out'*.PCSI;*") .nes. "" then delete/nolog 'out'*.PCSI;*
$ if f$search("''mat'*.*;*") .nes. "" then delete/nolog 'mat'*.*;*
$ copy/nolog 'inst'.LIB]LIBXML2.OLB 'mat'
$ copy/nolog 'inst'.INCLUDE.LIBXML]*.H 'mat'
$ copy/nolog [.OBJ_X86_64_CLANG]XMLLINT.EXE 'mat'
$ copy/nolog [.VMSPORT.KIT]LIBXML2$STARTUP.COM,README.VMS 'mat'
$ copy/nolog [.VMSPORT.KIT.DOC]*.* 'mat'
$ matspec = f$parse(mat,,,"DEVICE","NO_CONCEAL") + f$parse(mat,,,"DIRECTORY","NO_CONCEAL")
$!
$ write sys$output "MAKE_KIT: ''KIT_PRODUCER' ''base' LIBXML2 ''PCSI_VERSION' (LIBXML2 ''KIT_VERSION')"
$ product package LIBXML2 -
    /producer='KIT_PRODUCER' /base_system='base' /version='PCSI_VERSION' -
    /source=[.VMSPORT.KIT]LIBXML2-'base'.PCSI$DESC -
    /material='matspec' -
    /destination='out' -
    /format=sequential -
    /options=noconfirm /log
$ status = $status
$ kit = f$search("''out'*.PCSI")
$ if kit .nes. "" then write sys$output "MAKE_KIT: kit ", kit
$ if kit .eqs. "" then status = 44
$done:
$ set default 'saved_default'
$ exit status
