/* config.h - libxml2 for OpenVMS x86-64, built with VSI clang (LP64).

   Hand-written: upstream's configure cannot run on VMS.  libxml2 2.15 tests
   only these few facts; the answers come from the vms-php Phase 0 probes
   (clang on x86-64, docs/PHASE0.md there).  The feature switches
   (LIBXML_*_ENABLED) are in include/libxml/xmlversion.h, generated by
   tools/prepare.sh from upstream.conf's XML_OPTIONS. */
#ifndef VMS_LIBXML2_CONFIG_H
#define VMS_LIBXML2_CONFIG_H

/* declared in <sys/mman.h> and works (xmllint --memory) */
#define HAVE_DECL_MMAP 1
/* not on VMS: getentropy (libxml2 then seeds its hash randomisation from
   the time and an address), glob (only testapi/runtest use it), dlopen and
   shl_load (modules are off), readline/history (off) */
#define HAVE_DECL_GETENTROPY 0
#define HAVE_DECL_GLOB 0
/* threads are off (XML_OPTIONS): neither HAVE_POSIX_THREADS nor
   HAVE_WIN32_THREADS.  No destructor attribute: libxml2 would register
   xmlCleanupParser for image rundown, which the VMS linker does not run. */

#define HAVE_STDINT_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_STAT_H 1

/* the default catalog file://XML_SYSCONFDIR/xml/catalog; none on VMS */
#define XML_SYSCONFDIR "/sys$login"

#endif
